language: elixir
sudo: false
elixir:
  - 1.8
  - 1.9
otp_release:
  - 21.2
  - 22.0
env:
  - MIX_ENV=test
script:
  - mix test
cache:
  directories:
    - ~/.mix
    - ~/.hex
    - deps
    - _build
jobs:
  include:
    - stage: format
      env:
        - MIX_ENV=dev
      script: mix format --check-formatted
      elixir: 1.8
    - stage: dialyzer
      env:
        - MIX_ENV=dev
      before_script: travis_wait mix dialyzer --plt
      script: mix dialyzer --halt-exit-status
      elixir: 1.8
